# Development Environment Configuration
# Akan digunakan jika aplikasi dijalankan dengan profile 'dev' (spring.profiles.active=dev)

# JWT Configurations (Local dev default)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Security Configurations (Allow local origins for dev)
cors.allowed-origins=http://localhost:*,http://10.0.2.2:*,https://*.supabase.co
